// <auto-generated />
using System;
using Doantotnghiep_62131842.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Doantotnghiep_62131842.Migrations
{
    [DbContext(typeof(MamnonProjectContext))]
    [Migration("20240512121327_Addthang_namhocToChiphichinh")]
    partial class Addthang_namhocToChiphichinh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Chiphichinh", b =>
                {
                    b.Property<string>("Machiphichinh")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("machiphichinh");

                    b.Property<string>("ChildResumeId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Child_resume_ID");

                    b.Property<string>("Mahoatdong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("mahoatdong");

                    b.Property<decimal>("Tongchiphi")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tongchiphi");

                    b.Property<int>("Tongsobuoidiemdanh")
                        .HasColumnType("int")
                        .HasColumnName("tongsobuoidiemdanh");

                    b.Property<string>("thang_namhoc")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("thang_namhoc");

                    b.HasKey("Machiphichinh")
                        .HasName("PK__Chiphichinh__3B703D0CBF7CF768");

                    b.HasIndex("ChildResumeId");

                    b.HasIndex("Mahoatdong");

                    b.ToTable("Chiphichinh", (string)null);
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.ChitietgiaovienLop", b =>
                {
                    b.Property<string>("ChitietgvLId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Chitietgv_lID");

                    b.Property<string>("ClassId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ClassID");

                    b.Property<string>("Magiaovien")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Namhoc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("namhoc");

                    b.HasKey("ChitietgvLId")
                        .HasName("PK__chitietg__CB1D01924CCC8BAE");

                    b.HasIndex("ClassId");

                    b.HasIndex("Magiaovien");

                    b.ToTable("chitietgiaovien_lop", (string)null);
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Chude", b =>
                {
                    b.Property<string>("Machude")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("machude");

                    b.Property<string>("Tenchude")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tenchude");

                    b.HasKey("Machude")
                        .HasName("PK__Chude__3B703D0CBF7CF768");

                    b.ToTable("Chude", (string)null);
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Danhmonantheongay", b =>
                {
                    b.Property<string>("Malichngay")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Buoichieu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("buoichieu");

                    b.Property<string>("Buoisang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("buoisang");

                    b.Property<string>("Buoitrua")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("buoitrua");

                    b.Property<string>("MenuId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Menu_ID");

                    b.Property<DateTime?>("Ngay")
                        .HasColumnType("datetime")
                        .HasColumnName("ngay");

                    b.Property<string>("Trangmieng")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("trangmieng");

                    b.HasKey("Malichngay")
                        .HasName("PK__Danhmona__A3162DB41A6B35E6");

                    b.HasIndex("MenuId");

                    b.ToTable("Danhmonantheongay", (string)null);
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Donnhaphoc", b =>
                {
                    b.Property<string>("AfaId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("AFA_ID");

                    b.Property<DateTime?>("Batdauhoc")
                        .HasColumnType("datetime")
                        .HasColumnName("batdauhoc");

                    b.Property<string>("Lophocmongmuon")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("lophocmongmuon")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namhoc")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("namhoc")
                        .IsFixedLength();

                    b.Property<DateTime?>("Ngaytaodon")
                        .HasColumnType("datetime");

                    b.Property<string>("SdtLienhe")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("Sdt_lienhe");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("AfaId")
                        .HasName("PK__Donnhaph__2936EA35D0ABCAF8");

                    b.ToTable("Donnhaphoc", (string)null);
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.DsthucDon", b =>
                {
                    b.Property<string>("MenuId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Menu_ID");

                    b.Property<DateTime?>("Ngaybatdau")
                        .HasColumnType("datetime")
                        .HasColumnName("ngaybatdau");

                    b.Property<DateTime?>("Ngayketthuc")
                        .HasColumnType("datetime")
                        .HasColumnName("ngayketthuc");

                    b.HasKey("MenuId")
                        .HasName("PK__DSThucDo__69E7231872E0A6D3");

                    b.ToTable("DSThucDon", (string)null);
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Giaovien", b =>
                {
                    b.Property<string>("Magiaovien")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Diachi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("diachi");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Maloaigiaovien")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maloaigiaovien");

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("datetime")
                        .HasColumnName("ngaysinh");

                    b.Property<string>("Sodienthoai")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("sodienthoai");

                    b.Property<string>("Tengiaovien")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Magiaovien")
                        .HasName("PK__Giaovien__38993AE7A5975DCD");

                    b.HasIndex("Maloaigiaovien");

                    b.ToTable("Giaovien", (string)null);
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Hoatdong", b =>
                {
                    b.Property<string>("Mahoatdong")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("Chiphi")
                        .HasColumnType("int")
                        .HasColumnName("chiphi");

                    b.Property<string>("Tenhoatdong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenhoatdong");

                    b.HasKey("Mahoatdong")
                        .HasName("PK__Hoatdong__698E65434BF059F9");

                    b.ToTable("Hoatdong", (string)null);
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Hoatdongchinh", b =>
                {
                    b.Property<string>("MaHoatdongchinh")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maHoatdongchinh");

                    b.Property<string>("Mahoatdong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("mahoatdong");

                    b.HasKey("MaHoatdongchinh")
                        .HasName("PK_Hoatdongchinh");

                    b.ToTable("Hoatdongchinh", (string)null);
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Hocvien", b =>
                {
                    b.Property<string>("ChildResumeId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Child_resume_ID");

                    b.Property<string>("AfaId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("AFA_ID");

                    b.Property<string>("ClassId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ClassID");

                    b.Property<string>("CurrentHealthStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("current_health_status");

                    b.Property<string>("Diachi")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("diachi");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit")
                        .HasColumnName("gender");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("InformationDif")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("information_dif");

                    b.Property<string>("MedicalHistory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("medical_history");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("name");

                    b.Property<string>("ParentResumeId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Parent_resume_ID");

                    b.HasKey("ChildResumeId")
                        .HasName("PK__Hocvien__7FE0700297BEBB61");

                    b.HasIndex("AfaId");

                    b.HasIndex("ClassId");

                    b.HasIndex("ParentResumeId");

                    b.ToTable("Hocvien", (string)null);
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.ImagesTinhtrangsuckhoe", b =>
                {
                    b.Property<string>("ImagesTinhtrangsuckhoeId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ImagesTinhtrangsuckhoeID");

                    b.Property<string>("LinkImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TtskId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ttsk_id");

                    b.HasKey("ImagesTinhtrangsuckhoeId")
                        .HasName("PK__ImagesTi__DC283E3D8724F0C3");

                    b.HasIndex("TtskId");

                    b.ToTable("ImagesTinhtrangsuckhoe", (string)null);
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Loaigiaovien", b =>
                {
                    b.Property<string>("Maloaigiaovien")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maloaigiaovien");

                    b.Property<string>("Tenloaigiaovien")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tenloaigiaovien");

                    b.HasKey("Maloaigiaovien")
                        .HasName("PK__Loaigiao__F615CD290B497571");

                    b.ToTable("Loaigiaovien", (string)null);
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Loailop", b =>
                {
                    b.Property<string>("ClasstypeId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Classtype_ID");

                    b.Property<string>("NameClasstype")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Name_classtype");

                    b.HasKey("ClasstypeId")
                        .HasName("PK__Loailop__A454543F9567BAAA");

                    b.ToTable("Loailop", (string)null);
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Lop", b =>
                {
                    b.Property<string>("ClassId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ClassID");

                    b.Property<string>("ClasstypeId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Classtype_ID");

                    b.Property<string>("NameClass")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Name_class");

                    b.Property<string>("Namhoc")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("namhoc");

                    b.Property<int?>("Siso")
                        .HasColumnType("int")
                        .HasColumnName("siso");

                    b.HasKey("ClassId")
                        .HasName("PK__Lop__CB1927A05562A173");

                    b.HasIndex("ClasstypeId");

                    b.ToTable("Lop", (string)null);
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Phieubengoan", b =>
                {
                    b.Property<string>("PhbnId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("PHBN_ID");

                    b.Property<string>("ChildResumeId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Child_resume_ID");

                    b.Property<string>("Hanhvi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hanhvi");

                    b.Property<string>("Magiaovien")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("Ngaydanhgia")
                        .HasColumnType("datetime");

                    b.Property<string>("Thaido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("thaido");

                    b.Property<string>("Thanhtich")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("thanhtich");

                    b.HasKey("PhbnId")
                        .HasName("PK__Phieuben__AC209BDBB35BB4E5");

                    b.HasIndex("ChildResumeId");

                    b.HasIndex("Magiaovien");

                    b.ToTable("Phieubengoan", (string)null);
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Phieudiemdanh", b =>
                {
                    b.Property<string>("DiemdanhId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Diemdanh_id");

                    b.Property<string>("ChildResumeId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Child_resume_ID");

                    b.Property<string>("Namhoc")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("namhoc");

                    b.Property<DateTime?>("Ngayhoc")
                        .HasColumnType("datetime")
                        .HasColumnName("ngayhoc");

                    b.HasKey("DiemdanhId")
                        .HasName("PK__Phieudie__0AEC22A8655AA399");

                    b.HasIndex("ChildResumeId");

                    b.ToTable("Phieudiemdanh", (string)null);
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Phuhuynh", b =>
                {
                    b.Property<string>("ParentResumeId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Parent_resume_ID");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime")
                        .HasColumnName("Date_of_birth");

                    b.Property<string>("Diachi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("diachi");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit")
                        .HasColumnName("gender");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ImageURL");

                    b.Property<string>("JobParent")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Job_parent");

                    b.Property<string>("NameP")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NameP2")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("NumberOfChildren")
                        .HasColumnType("int")
                        .HasColumnName("number_of_children");

                    b.Property<string>("Phone1")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Phone2")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.HasKey("ParentResumeId")
                        .HasName("PK__Phuhuynh__42CFE641FFCBACBF");

                    b.ToTable("Phuhuynh", (string)null);
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JwtID");

                    b.Property<string>("NguoidungUsername")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoidungUsername");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("RoleID");

                    b.Property<string>("Rolename")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__8AFACE3ACB81125A");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Suckhoedinhki", b =>
                {
                    b.Property<string>("SkdkId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("skdk_id");

                    b.Property<string>("Benhlykhac")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("benhlykhac");

                    b.Property<string>("Cannang")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("cannang");

                    b.Property<string>("Chieucao")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("chieucao");

                    b.Property<string>("ChildResumeId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Child_resume_ID");

                    b.Property<string>("Ghichubacsy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ghichubacsy");

                    b.Property<string>("Magiaovien")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Ngaykiemtra")
                        .HasColumnType("datetime")
                        .HasColumnName("ngaykiemtra");

                    b.HasKey("SkdkId")
                        .HasName("PK__Suckhoed__0D4A67825ED6C99D");

                    b.HasIndex("ChildResumeId");

                    b.HasIndex("Magiaovien");

                    b.ToTable("Suckhoedinhki", (string)null);
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Thoikhoabieu", b =>
                {
                    b.Property<string>("Matkb")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("matkb");

                    b.Property<string>("ClassId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ClassID");

                    b.Property<string>("Magiaovien")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("Ngaybatdau")
                        .HasColumnType("datetime")
                        .HasColumnName("ngaybatdau");

                    b.Property<DateTime?>("Ngayketthuc")
                        .HasColumnType("datetime")
                        .HasColumnName("ngayketthuc");

                    b.HasKey("Matkb")
                        .HasName("PK__Thoikhoa__1489A4D151953889");

                    b.HasIndex("Magiaovien");

                    b.ToTable("Thoikhoabieu", (string)null);
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Tiethoc", b =>
                {
                    b.Property<string>("Tiethocid")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("tiethocid");

                    b.Property<string>("Matkb")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("matkb");

                    b.Property<DateTime?>("Ngayhoc")
                        .HasColumnType("datetime")
                        .HasColumnName("ngayhoc");

                    b.Property<DateTime?>("Thoigianbatdauhoc")
                        .HasColumnType("datetime")
                        .HasColumnName("thoigianbatdauhoc");

                    b.Property<DateTime?>("Thoigianketthuchoc")
                        .HasColumnType("datetime")
                        .HasColumnName("thoigianketthuchoc");

                    b.Property<string>("Tieuthoc")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tieuthoc");

                    b.HasKey("Tiethocid")
                        .HasName("PK__Tiethoc__FB62F9B479824779");

                    b.HasIndex("Matkb");

                    b.ToTable("Tiethoc", (string)null);
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Tinhtrangsuckhoe", b =>
                {
                    b.Property<string>("TtskId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ttsk_id");

                    b.Property<string>("ChildResumeId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Child_resume_ID");

                    b.Property<string>("Magiaovien")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("Ngaykiemtra")
                        .HasColumnType("datetime")
                        .HasColumnName("ngaykiemtra");

                    b.Property<string>("Nhietdo")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("nhietdo");

                    b.Property<string>("Thaidohochanh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("thaidohochanh");

                    b.Property<string>("Trangthaian")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trangthaian");

                    b.Property<string>("Trangthaingu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trangthaingu");

                    b.HasKey("TtskId")
                        .HasName("PK__Tinhtran__43E94AF57479EDED");

                    b.HasIndex("ChildResumeId");

                    b.HasIndex("Magiaovien");

                    b.ToTable("Tinhtrangsuckhoe", (string)null);
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("UserID");

                    b.Property<string>("Magiaovien")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Mail")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ParentResumeId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Parent_resume_ID");

                    b.Property<string>("Password")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("password");

                    b.Property<string>("RoleId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("RoleID");

                    b.Property<string>("Username")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCACF730E990");

                    b.HasIndex("Magiaovien");

                    b.HasIndex("ParentResumeId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Ykien", b =>
                {
                    b.Property<string>("OpinionId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("opinion_ID");

                    b.Property<string>("Giaiphap")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("giaiphap");

                    b.Property<string>("Machude")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("machude");

                    b.Property<string>("NoteOpinion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Note_Opinion");

                    b.Property<string>("ParentResumeId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Parent_resume_ID");

                    b.HasKey("OpinionId")
                        .HasName("PK__Ykien__3906968FA209ED15");

                    b.HasIndex("Machude");

                    b.HasIndex("ParentResumeId");

                    b.ToTable("Ykien", (string)null);
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Chiphichinh", b =>
                {
                    b.HasOne("Doantotnghiep_62131842.Entity.Hocvien", "hocvien")
                        .WithMany()
                        .HasForeignKey("ChildResumeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Doantotnghiep_62131842.Entity.Hoatdong", "Hoatdong")
                        .WithMany()
                        .HasForeignKey("Mahoatdong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hoatdong");

                    b.Navigation("hocvien");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.ChitietgiaovienLop", b =>
                {
                    b.HasOne("Doantotnghiep_62131842.Entity.Lop", "Class")
                        .WithMany("ChitietgiaovienLops")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__chitietgi__Class__5AEE82B9");

                    b.HasOne("Doantotnghiep_62131842.Entity.Giaovien", "MagiaovienNavigation")
                        .WithMany("ChitietgiaovienLops")
                        .HasForeignKey("Magiaovien")
                        .HasConstraintName("FK__chitietgi__Magia__59FA5E80");

                    b.Navigation("Class");

                    b.Navigation("MagiaovienNavigation");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Danhmonantheongay", b =>
                {
                    b.HasOne("Doantotnghiep_62131842.Entity.DsthucDon", "Menu")
                        .WithMany("Danhmonantheongays")
                        .HasForeignKey("MenuId")
                        .HasConstraintName("FK__Danhmonan__Menu___5165187F");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Giaovien", b =>
                {
                    b.HasOne("Doantotnghiep_62131842.Entity.Loaigiaovien", "MaloaigiaovienNavigation")
                        .WithMany("Giaoviens")
                        .HasForeignKey("Maloaigiaovien")
                        .HasConstraintName("FK__Giaovien__maloai__398D8EEE");

                    b.Navigation("MaloaigiaovienNavigation");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Hocvien", b =>
                {
                    b.HasOne("Doantotnghiep_62131842.Entity.Donnhaphoc", "Afa")
                        .WithMany("Hocviens")
                        .HasForeignKey("AfaId")
                        .HasConstraintName("FK__Hocvien__AFA_ID__45F365D3");

                    b.HasOne("Doantotnghiep_62131842.Entity.Lop", "Class")
                        .WithMany("Hocviens")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__Hocvien__ClassID__46E78A0C");

                    b.HasOne("Doantotnghiep_62131842.Entity.Phuhuynh", "ParentResume")
                        .WithMany("Hocviens")
                        .HasForeignKey("ParentResumeId")
                        .HasConstraintName("FK__Hocvien__Parent___44FF419A");

                    b.Navigation("Afa");

                    b.Navigation("Class");

                    b.Navigation("ParentResume");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.ImagesTinhtrangsuckhoe", b =>
                {
                    b.HasOne("Doantotnghiep_62131842.Entity.Tinhtrangsuckhoe", "Ttsk")
                        .WithMany("ImagesTinhtrangsuckhoes")
                        .HasForeignKey("TtskId")
                        .HasConstraintName("FK__ImagesTin__ttsk___656C112C");

                    b.Navigation("Ttsk");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Lop", b =>
                {
                    b.HasOne("Doantotnghiep_62131842.Entity.Loailop", "Classtype")
                        .WithMany("Lops")
                        .HasForeignKey("ClasstypeId")
                        .HasConstraintName("FK__Lop__Classtype_I__403A8C7D");

                    b.Navigation("Classtype");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Phieubengoan", b =>
                {
                    b.HasOne("Doantotnghiep_62131842.Entity.Hocvien", "ChildResume")
                        .WithMany("Phieubengoans")
                        .HasForeignKey("ChildResumeId")
                        .HasConstraintName("FK__Phieubeng__Child__5DCAEF64");

                    b.HasOne("Doantotnghiep_62131842.Entity.Giaovien", "MagiaovienNavigation")
                        .WithMany("Phieubengoans")
                        .HasForeignKey("Magiaovien")
                        .HasConstraintName("FK__Phieubeng__Magia__5EBF139D");

                    b.Navigation("ChildResume");

                    b.Navigation("MagiaovienNavigation");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Phieudiemdanh", b =>
                {
                    b.HasOne("Doantotnghiep_62131842.Entity.Hocvien", "ChildResume")
                        .WithMany("Phieudiemdanhs")
                        .HasForeignKey("ChildResumeId")
                        .HasConstraintName("FK__Phieudiem__Child__68487DD7");

                    b.Navigation("ChildResume");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.RefreshToken", b =>
                {
                    b.HasOne("Doantotnghiep_62131842.Entity.User", "NguoidungUsernameNavigation")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("NguoidungUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_Nguoidung_Username");

                    b.Navigation("NguoidungUsernameNavigation");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Suckhoedinhki", b =>
                {
                    b.HasOne("Doantotnghiep_62131842.Entity.Hocvien", "ChildResume")
                        .WithMany("Suckhoedinhkis")
                        .HasForeignKey("ChildResumeId")
                        .HasConstraintName("FK__Suckhoedi__Child__571DF1D5");

                    b.HasOne("Doantotnghiep_62131842.Entity.Giaovien", "MagiaovienNavigation")
                        .WithMany("Suckhoedinhkis")
                        .HasForeignKey("Magiaovien")
                        .HasConstraintName("FK__Suckhoedi__Magia__5629CD9C");

                    b.Navigation("ChildResume");

                    b.Navigation("MagiaovienNavigation");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Thoikhoabieu", b =>
                {
                    b.HasOne("Doantotnghiep_62131842.Entity.Giaovien", "MagiaovienNavigation")
                        .WithMany("Thoikhoabieus")
                        .HasForeignKey("Magiaovien")
                        .HasConstraintName("FK__Thoikhoab__Magia__6FE99F9F");

                    b.Navigation("MagiaovienNavigation");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Tiethoc", b =>
                {
                    b.HasOne("Doantotnghiep_62131842.Entity.Thoikhoabieu", "MatkbNavigation")
                        .WithMany("Tiethocs")
                        .HasForeignKey("Matkb")
                        .HasConstraintName("FK__Tiethoc__matkb__72C60C4A");

                    b.Navigation("MatkbNavigation");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Tinhtrangsuckhoe", b =>
                {
                    b.HasOne("Doantotnghiep_62131842.Entity.Hocvien", "ChildResume")
                        .WithMany("Tinhtrangsuckhoes")
                        .HasForeignKey("ChildResumeId")
                        .HasConstraintName("FK__Tinhtrang__Child__619B8048");

                    b.HasOne("Doantotnghiep_62131842.Entity.Giaovien", "MagiaovienNavigation")
                        .WithMany("Tinhtrangsuckhoes")
                        .HasForeignKey("Magiaovien")
                        .HasConstraintName("FK__Tinhtrang__Magia__628FA481");

                    b.Navigation("ChildResume");

                    b.Navigation("MagiaovienNavigation");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.User", b =>
                {
                    b.HasOne("Doantotnghiep_62131842.Entity.Giaovien", "MagiaovienNavigation")
                        .WithMany("Users")
                        .HasForeignKey("Magiaovien")
                        .HasConstraintName("FK__Users__Magiaovie__787EE5A0");

                    b.HasOne("Doantotnghiep_62131842.Entity.Phuhuynh", "ParentResume")
                        .WithMany("Users")
                        .HasForeignKey("ParentResumeId")
                        .HasConstraintName("FK__Users__Parent_re__797309D9");

                    b.HasOne("Doantotnghiep_62131842.Entity.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__Users__RoleID__778AC167");

                    b.Navigation("MagiaovienNavigation");

                    b.Navigation("ParentResume");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Ykien", b =>
                {
                    b.HasOne("Doantotnghiep_62131842.Entity.Chude", "MachudeNavigation")
                        .WithMany("Ykiens")
                        .HasForeignKey("Machude")
                        .HasConstraintName("FK__Ykien__machude__4BAC3F29");

                    b.HasOne("Doantotnghiep_62131842.Entity.Phuhuynh", "ParentResume")
                        .WithMany("Ykiens")
                        .HasForeignKey("ParentResumeId")
                        .HasConstraintName("FK__Ykien__Parent_re__4CA06362");

                    b.Navigation("MachudeNavigation");

                    b.Navigation("ParentResume");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Chude", b =>
                {
                    b.Navigation("Ykiens");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Donnhaphoc", b =>
                {
                    b.Navigation("Hocviens");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.DsthucDon", b =>
                {
                    b.Navigation("Danhmonantheongays");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Giaovien", b =>
                {
                    b.Navigation("ChitietgiaovienLops");

                    b.Navigation("Phieubengoans");

                    b.Navigation("Suckhoedinhkis");

                    b.Navigation("Thoikhoabieus");

                    b.Navigation("Tinhtrangsuckhoes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Hocvien", b =>
                {
                    b.Navigation("Phieubengoans");

                    b.Navigation("Phieudiemdanhs");

                    b.Navigation("Suckhoedinhkis");

                    b.Navigation("Tinhtrangsuckhoes");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Loaigiaovien", b =>
                {
                    b.Navigation("Giaoviens");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Loailop", b =>
                {
                    b.Navigation("Lops");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Lop", b =>
                {
                    b.Navigation("ChitietgiaovienLops");

                    b.Navigation("Hocviens");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Phuhuynh", b =>
                {
                    b.Navigation("Hocviens");

                    b.Navigation("Users");

                    b.Navigation("Ykiens");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Thoikhoabieu", b =>
                {
                    b.Navigation("Tiethocs");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.Tinhtrangsuckhoe", b =>
                {
                    b.Navigation("ImagesTinhtrangsuckhoes");
                });

            modelBuilder.Entity("Doantotnghiep_62131842.Entity.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
